@GPMLogin.WebApi_HostAddress = http://localhost:5152

### Collect fingerprint data (Headful)
GET {{GPMLogin.WebApi_HostAddress}}/gpm-login/fp-collect
Accept: application/json

### Collect fingerprint data (Headless)
GET {{GPMLogin.WebApi_HostAddress}}/gpm-login/fp-collect?headless=true
Accept: application/json

